import { strToU8, zipSync } from 'fflate'

import { createProjectRuntimeFiles } from './normalize'
import type { GeneratedProject } from './types'

export type ProjectExportFiles = Record<string, string>

/**
 * Build the complete, portable project tree without exposing host-only paths or configuration.
 * The runtime helper revalidates model-controlled files and owns scaffold/static
 * host policy so generated files cannot override it.
 */
export function createProjectExportFiles(project: GeneratedProject): ProjectExportFiles {
  return createProjectRuntimeFiles(project)
}

const WINDOWS_RESERVED_NAME = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i

const getProjectDirectoryName = (title: string): string => {
  const candidate = title
    .normalize('NFKC')
    .replace(/[^a-z0-9._-]+/gi, '-')
    .replace(/^[. -]+|[. -]+$/g, '')
    .slice(0, 96)
    .replace(/[. -]+$/g, '')

  return candidate && !WINDOWS_RESERVED_NAME.test(candidate) ? candidate : 'generated-project'
}

const assertArchivePaths = (files: ProjectExportFiles): void => {
  const paths = Object.keys(files)
  const normalizedPaths = paths.map((path) => path.normalize('NFC').toLowerCase())
  const seen = new Set<string>()

  normalizedPaths.forEach((path, index) => {
    if (seen.has(path)) throw new Error(`项目归档路径冲突：${paths[index]}`)
    seen.add(path)
  })

  const filePaths = new Set(normalizedPaths)
  for (const path of paths) {
    const segments = path.split('/')
    for (let index = 1; index < segments.length; index += 1) {
      const parent = segments.slice(0, index).join('/').normalize('NFC').toLowerCase()
      if (filePaths.has(parent)) throw new Error(`项目文件与目录路径冲突：${path}`)
    }
  }
}

const createWebProjectReadme = (project: GeneratedProject): string => {
  const title = project.title.replace(/[\r\n`]/g, ' ').trim() || 'Generated project'
  return `# ${title}

This project was generated by Mosaic.

## Run locally

Requires Node.js 22 or newer.

\`\`\`bash
npm ci
npm run dev
\`\`\`
`
}

/**
 * Package the same validated file tree used by the in-browser runtime as a
 * conventional ZIP archive. A single top-level directory keeps extracted
 * projects together and prevents files from scattering into the download
 * directory.
 */
export function createProjectZip(project: GeneratedProject): Uint8Array {
  const files = createProjectExportFiles(project)
  assertArchivePaths(files)
  const directory = `${getProjectDirectoryName(project.title)}/`
  const archiveFiles: Record<string, Uint8Array> = {}

  for (const [path, content] of Object.entries(files)) {
    archiveFiles[`${directory}${path}`] = strToU8(content)
  }

  if (project.kind === 'web') {
    archiveFiles[`${directory}README.md`] = strToU8(createWebProjectReadme(project))
  }

  return zipSync(archiveFiles, { level: 6 })
}

export function downloadProjectBundle(project: GeneratedProject): void {
  const archive = createProjectZip(project)
  const blob = new Blob([new Uint8Array(archive)], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${getProjectDirectoryName(project.title)}.zip`
  anchor.style.display = 'none'
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}
