import { CheckCircle2, Database, Info, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { Provider } from '../types'

interface SettingsViewProps { providers: Provider[]; promptLength: number; selectedCount: number; onRestore: () => void; onClear: () => void }

export function SettingsView({ providers, promptLength, selectedCount, onRestore, onClear }: SettingsViewProps) {
  const { t } = useTranslation()
  const configuredCount = providers.filter((provider) => provider.apiKey.trim()).length
  return (
    <div className="mx-auto w-full max-w-[1120px] min-w-0 px-4 pb-20 pt-[52px] max-[580px]:px-[15px] max-[580px]:pt-8">
      <div className="mb-9 min-w-0"><p className="eyebrow mb-2 font-mono text-[10px] uppercase tracking-[0.12em] text-faint">03 / PREFERENCES</p><h1 className="m-0 max-w-full break-words text-[39px] font-medium tracking-[-0.06em] max-[580px]:text-[34px]">{t('settings.title')}</h1><p className="mt-2 max-w-[68ch] break-words text-[13px] text-muted">{t('settings.subtitle')}</p></div>
      <div className="grid min-w-0 gap-3.5 max-[820px]:grid-cols-1">
        <section className="min-w-0 rounded-[10px] border border-[#2d333b] bg-surface p-5">
          <div className="flex min-w-0 items-start gap-2.5 border-b border-line-soft pb-4"><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-mint/10 text-mint"><Database aria-hidden="true" size={18} /></div><div className="min-w-0"><h2 className="mb-1.5 mt-0.5 break-words text-[15px] font-medium">{t('settings.localData')}</h2><p className="m-0 max-w-[65ch] break-words text-[11px] leading-[1.45] text-[#737b82]">{t('settings.localCopy')}</p></div></div>
          <div className="my-4 grid grid-cols-2 gap-px overflow-hidden rounded-[7px] border border-line-soft bg-line-soft"><div className="flex min-w-0 flex-col gap-1.5 bg-surface-soft p-3"><span className="break-words text-[10px] text-muted">{t('settings.providerCount')}</span><strong className="font-mono text-[15px] font-medium text-ink">{providers.length}</strong></div><div className="flex min-w-0 flex-col gap-1.5 bg-surface-soft p-3"><span className="break-words text-[10px] text-muted">{t('settings.configuredCount')}</span><strong className="font-mono text-[15px] font-medium text-ink">{configuredCount}</strong></div><div className="flex min-w-0 flex-col gap-1.5 bg-surface-soft p-3"><span className="break-words text-[10px] text-muted">{t('settings.selectedCount')}</span><strong className="font-mono text-[15px] font-medium text-ink">{selectedCount}</strong></div><div className="flex min-w-0 flex-col gap-1.5 bg-surface-soft p-3"><span className="break-words text-[10px] text-muted">{t('settings.promptLength')}</span><strong className="font-mono text-[15px] font-medium text-ink">{promptLength}</strong></div></div>
          <div className="flex flex-wrap gap-2 max-[580px]:flex-col"><button className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-[#353b44] bg-surface-soft px-3 text-[11px] font-semibold text-ink transition-colors hover:bg-surface-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mint/70 max-[580px]:w-full" type="button" onClick={onRestore}><RotateCcw aria-hidden="true" size={15} />{t('settings.restore')}</button><button className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-red/25 bg-transparent px-3 text-[11px] font-semibold text-red transition-colors hover:bg-red/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red/70 max-[580px]:w-full" type="button" onClick={onClear}><Trash2 aria-hidden="true" size={15} />{t('settings.clear')}</button></div>
        </section>
        <section className="min-w-0 rounded-[10px] border border-[#2d333b] bg-surface p-5">
          <div className="flex min-w-0 items-start gap-2.5 border-b border-line-soft pb-4"><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-violet/10 text-violet"><ShieldCheck aria-hidden="true" size={18} /></div><div className="min-w-0"><h2 className="mb-1.5 mt-0.5 break-words text-[15px] font-medium">{t('settings.security')}</h2><p className="m-0 max-w-[65ch] break-words text-[11px] leading-[1.45] text-[#737b82]">{t('settings.securityCopy')}</p></div></div>
          <div className="grid gap-3.5 py-4"><div className="flex min-w-0 items-center gap-2 text-[11px] text-[#b2b8b7]"><CheckCircle2 aria-hidden="true" className="shrink-0 text-mint" size={16} /><span className="min-w-0 break-words">{t('settings.localOnly')}</span></div><div className="flex min-w-0 items-center gap-2 text-[11px] text-[#b2b8b7]"><CheckCircle2 aria-hidden="true" className="shrink-0 text-mint" size={16} /><span className="min-w-0 break-words">{t('settings.sandbox')}</span></div><div className="flex min-w-0 items-center gap-2 text-[11px] text-[#b2b8b7]"><CheckCircle2 aria-hidden="true" className="shrink-0 text-mint" size={16} /><span className="min-w-0 break-words">{t('settings.confirm')}</span></div></div>
          <div className="flex min-w-0 items-start gap-2 rounded-md border border-yellow/15 bg-yellow/7 p-2.5 text-[#9d9277]"><Info aria-hidden="true" className="mt-px shrink-0 text-yellow" size={15} /><p className="m-0 min-w-0 break-words text-[10px] leading-[1.5]">{t('settings.warning')}</p></div>
        </section>
      </div>
      <div className="mt-10 min-w-0"><div className="mb-4"><h2 className="m-0 break-words text-base font-medium tracking-[-0.02em]">{t('settings.shortcuts')}</h2><span className="mt-1 block max-w-[60ch] break-words text-[11px] text-faint">{t('settings.shortcutCopy')}</span></div><div className="grid min-w-0 gap-2.5 max-[580px]:grid-cols-1"><div className="flex min-w-0 items-center gap-1.5 rounded-[7px] border border-line-soft bg-surface px-3 py-3 text-[11px] text-[#858d92]"><span className="min-w-0 flex-1 break-words">{t('settings.run')}</span><kbd className="min-w-[22px] shrink-0 rounded border border-[#3b424a] bg-[#252a31] px-1.5 py-1 text-center font-mono text-[9px] text-[#9da5a8]">Ctrl/⌘</kbd><kbd className="min-w-[22px] shrink-0 rounded border border-[#3b424a] bg-[#252a31] px-1.5 py-1 text-center font-mono text-[9px] text-[#9da5a8]">↵</kbd></div><div className="flex min-w-0 items-center gap-1.5 rounded-[7px] border border-line-soft bg-surface px-3 py-3 text-[11px] text-[#858d92]"><span className="min-w-0 flex-1 break-words">{t('settings.close')}</span><kbd className="min-w-[22px] shrink-0 rounded border border-[#3b424a] bg-[#252a31] px-1.5 py-1 text-center font-mono text-[9px] text-[#9da5a8]">Esc</kbd></div><div className="flex min-w-0 items-center gap-1.5 rounded-[7px] border border-line-soft bg-surface px-3 py-3 text-[11px] text-[#858d92]"><span className="min-w-0 flex-1 break-words">{t('settings.add')}</span><kbd className="min-w-[22px] shrink-0 rounded border border-[#3b424a] bg-[#252a31] px-1.5 py-1 text-center font-mono text-[9px] text-[#9da5a8]">Ctrl/⌘</kbd><kbd className="min-w-[22px] shrink-0 rounded border border-[#3b424a] bg-[#252a31] px-1.5 py-1 text-center font-mono text-[9px] text-[#9da5a8]">K</kbd></div></div></div>
    </div>
  )
}
