import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const resources = {
  zh: {
    translation: {
      nav: { studio: 'Studio', menu: '打开导航', workspace: '工作区', providers: '提供商', settings: '设置', localOnly: '仅本地', configured: '已配置密钥', manage: '管理连接', localData: '数据保存在此浏览器', help: '帮助与快捷键' },
      topbar: { local: '本地工作区', security: '安全说明', securityInfo: '所有密钥和配置都只保存在当前浏览器。', settings: '设置' },
      studio: { kicker: '多模型 Playground', title: '让一个想法，', titleAccent: '同时发生。', subtitle: '把同一份 brief 交给多个模型，比较它们如何理解你的想法。', canvas: '画布已就绪', start: '选择一个方向开始' },
      prompt: { label: '给模型一个方向', shortcut: '⌘/Ctrl + Enter 运行', quickStart: '快速开始', placeholder: '描述你想看到的页面、交互和氛围…', pageLabel: '页面提示词', templatesLabel: '提示词模板', demoSwitch: '切换演示模式', demo: '演示模式', noApi: '不调用 API', useKeys: '使用已配置密钥', generate: '生成页面', generating: '生成中…', empty: '先写一段提示词再开始生成', modelsReady: '{{count}} 个模型已就绪', selectModels: '选择模型', parallel: '将并排比较结果', multiSelect: '可多选并行运行' },
      templates: { saas: 'SaaS 发布页', portfolio: '个人作品集', dashboard: '数据仪表盘' },
      templatePrompts: { saas: '为一个 AI 团队协作产品设计发布页。风格克制、精确、有高级感，包含产品界面预览、核心功能、社会证明、价格卡片与 FAQ。', portfolio: '为一位独立产品设计师设计个人作品集。首页要大胆但不浮夸，突出精选项目、个人简介与联系入口，并适配移动端。', dashboard: '设计一个创作者数据仪表盘，包含关键指标、趋势图、内容列表和侧边导航。界面需要专业、清晰且具有响应式布局。' },
      models: { set: '模型集合', target: '本次运行目标', none: '还没有选择模型', selected: '已选择 {{count}} 个模型', parallel: '{{count}} 个并行任务', multi: '可多选', start: '从模型选择器中添加本次运行目标', removed: '这个模型已经从提供商配置中移除', providerMissing: '找不到对应的提供商配置', select: '选择要并行运行的模型', close: '关闭模型选择', empty: '先添加一个提供商和模型', notConfigured: '未配置', clear: '清除选择', manage: '管理提供商' },
      results: { title: '生成结果', demo: '当前为演示模式 · 不会调用外部 API', sandbox: '静态结果隔离渲染 · 工程结果按需运行', reload: '重新载入示例', demoLoaded: '已加载示例结果', grid: '宫格视图', queued: '排队中', running: '生成中', success: '产物就绪', error: '失败', copy: 'HTML 已复制到剪贴板', copyLabel: '复制 HTML', projectCopied: '项目 JSON 已复制到剪贴板', copyProjectLabel: '复制项目 JSON', previewTitle: '页面预览', copyError: '复制失败，请检查浏览器权限', building: '模型正在构建设计', wait: '通常需要几秒钟，请稍候', waiting: '等待运行', cancelled: '已取消', cancelledCopy: '这次运行已停止', failed: '这次没有跑通', retry: '重试', expand: '放大预览', remove: '移除结果', empty: '暂无可预览的内容', staticBadge: '静态', projectBadge: '工程', fileCount: '{{count}} 个文件', runProject: '运行项目', web: { booting: '正在启动 WebContainer', mounting: '正在挂载项目文件', installing: '正在安装依赖', starting: '正在启动项目', ready: '项目预览已就绪', stopping: '正在停止项目', error: '项目运行失败', unsupported: '当前浏览器不支持 WebContainer', errorDescription: '请查看下方截断日志以定位启动问题。', unsupportedDescription: '请使用支持 WebContainer 的现代浏览器后重试。', switching: '当前任务排队中，正在切换项目', stop: '停止', singleRuntime: '共享活动工程', waitingDescription: '首次运行需要安装依赖并启动开发服务器，请稍候。', previewUnavailable: '容器已就绪，但尚未提供预览地址。', logs: '运行日志' } },
      empty: { eyebrow: '准备就绪', title: '让想法同时发生', copy: '选择模型，写下一个方向，Mosaic 会把同一份提示词交给它们并行创作。', select: '选择模型', demo: '查看示例结果' },
      providers: { title: '提供商', count: '{{count}} 个提供商', subtitle: '连接你的模型服务，使用个人密钥在本地运行生成任务。', add: '添加提供商', securityTitle: '你的密钥只属于这个浏览器', securityCopy: '配置通过 Zustand persist 写入本机 localStorage。请使用测试密钥并设置供应商额度。', configured: '已配置', connected: '已连接的提供商', connectedCopy: '选择不同协议，组合你的模型池', none: '还没有提供商', noneCopy: '添加一个 API 服务和模型，开始你的第一次并行生成。', first: '添加第一个', addNew: '添加新的提供商', addNewCopy: 'OpenAI · Anthropic · Gemini · 兼容接口', keyReady: '密钥已配置', keyMissing: '等待配置 API Key', defaultUrl: 'SDK 默认地址', edit: '编辑提供商', delete: '删除提供商', deleteConfirm: '确定删除 {{name}} 吗？', deleted: '提供商已删除', footnote: '模型名称、Base URL 和密钥都由你掌控。Mosaic 不会代理或上传你的密钥。' },
      settings: { title: '设置', subtitle: '管理本地工作区状态和生成偏好。', localData: '本地数据', localCopy: '所有配置都保存在当前浏览器的 localStorage。', providerCount: '提供商', configuredCount: '已配置密钥', selectedCount: '已选模型', promptLength: '提示词长度', restore: '恢复默认配置', restoreConfirm: '恢复默认配置会覆盖当前提供商和提示词，确定继续吗？', restored: '已恢复默认配置', clear: '清除本地配置', clearConfirm: '确定清除当前浏览器中的所有本地配置吗？', cleared: '本地配置已清除', security: '安全边界', securityCopy: '这是个人 BYOK 工具，不是生产密钥托管服务。', localOnly: '密钥仅保存于本机浏览器', sandbox: '模型输出在 sandbox iframe 中预览', confirm: '生成前可逐个确认模型', warning: '生产环境请使用后端代理、限制额度，并避免把高价值密钥放进浏览器。', shortcuts: '快捷键', shortcutCopy: '让提示词流保持在你的节奏里', run: '运行生成', close: '关闭弹窗 / 预览', add: '添加提供商' },
      dialog: { add: '添加提供商', edit: '编辑提供商', description: '密钥只保存在当前浏览器的本地存储中，不会发送到 Mosaic 服务器。', name: '提供商名称', namePlaceholder: '例如：OpenRouter', protocol: '接口协议', baseUrl: 'Base URL', key: 'API Key', showKey: '显示 API Key', hideKey: '隐藏 API Key', models: '模型 ID', modelsPlaceholder: '每行一个模型，例如：\ngpt-4o\nmy-provider/model', urlHint: '切换协议时会同步默认地址；自定义地址请确认与模型服务匹配。', modelHint: '优先点击“获取模型”；如果服务不支持模型列表，可继续手动输入，每行一个。', fetchModels: '获取模型', fetchingModels: '正在获取…', modelsFetched: '已获取 {{count}} 个模型', apiKeyRequired: '请先填写 API Key', security: '这是个人 BYOK 工具。浏览器本地存储可被同源脚本读取，请使用测试密钥、设置额度并定期撤销。', cancel: '取消', save: '保存修改', delete: '删除提供商', added: '提供商已添加', updated: '提供商已更新' },
      theme: { label: '主题', appearance: '外观', dark: '暗黑', light: '明亮', system: '跟随系统', darkCopy: '深色工作区', lightCopy: '浅色工作区', systemCopy: '自动匹配设备' },
      language: { label: '语言', chinese: '中文', english: 'English' },
      providerKind: { openai: 'OpenAI', anthropic: 'Anthropic', gemini: 'Google Gemini', 'openai-compatible': 'OpenAI 兼容' },
      labels: { modelSet: '模型集合', directive: '01 / 指令', connections: '02 / 连接', preferences: '03 / 偏好设置', localConfig: '本地配置', personalWorkspace: '个人工作区', modelStudio: '模型工作室' },
      errors: { unknown: '发生未知错误', network: '网络请求失败', cancelled: '请求已取消', requestFailed: '请求失败：{{message}}', invalidResponse: '服务返回了无效响应', validationFailed: '表单验证失败' },
      validation: { name: '请输入 2–40 个字符的提供商名称', baseUrl: '仅允许 HTTPS 或本机 HTTP 地址', apiKey: '密钥长度异常', models: '至少添加一个模型' },
      common: { close: '关闭', loading: '加载中', demo: 'DEMO' },
    },
  },
  en: {
    translation: {
      nav: { studio: 'Studio', menu: 'Open navigation', workspace: 'Workspace', providers: 'Providers', settings: 'Settings', localOnly: 'Local only', configured: 'keys configured', manage: 'Manage connections', localData: 'Data stays in this browser', help: 'Help & shortcuts' },
      topbar: { local: 'Local workspace', security: 'Security note', securityInfo: 'All keys and settings stay in this browser.', settings: 'Settings' },
      studio: { kicker: 'MULTI-MODEL PLAYGROUND', title: 'Make one idea, ', titleAccent: 'happen in parallel.', subtitle: 'Send the same brief to multiple models and compare how they interpret your idea.', canvas: 'Canvas ready', start: 'Choose a direction to begin' },
      prompt: { label: 'Give the models a direction', shortcut: '⌘/Ctrl + Enter to run', quickStart: 'Quick start', placeholder: 'Describe the page, interaction and atmosphere you want…', pageLabel: 'Page prompt', templatesLabel: 'Prompt templates', demoSwitch: 'Toggle demo mode', demo: 'Demo mode', noApi: 'No API calls', useKeys: 'Use configured keys', generate: 'Generate pages', generating: 'Generating…', empty: 'Write a prompt before generating', modelsReady: '{{count}} models ready', modelsReady_one: '{{count}} model ready', modelsReady_other: '{{count}} models ready', selectModels: 'Select models', parallel: 'Compare results side by side', multiSelect: 'Select multiple models' },
      templates: { saas: 'SaaS launch page', portfolio: 'Portfolio', dashboard: 'Analytics dashboard' },
      templatePrompts: { saas: 'Design a launch page for an AI team collaboration product. Keep it precise and premium, with a product preview, key features, social proof, pricing, and FAQ.', portfolio: 'Design a portfolio for an independent product designer. Make the opening bold but refined, highlight selected work, biography, contact details, and mobile responsiveness.', dashboard: 'Design a creator analytics dashboard with key metrics, trend charts, a content list, and side navigation. The interface should feel professional, clear, and responsive.' },
      models: { set: 'MODEL SET', target: 'Run targets', none: 'No models selected', selected: '{{count}} models selected', selected_one: '{{count}} model selected', selected_other: '{{count}} models selected', parallel: '{{count}} parallel tasks', parallel_one: '{{count}} parallel task', parallel_other: '{{count}} parallel tasks', multi: 'Multi-select', start: 'Add run targets from the model picker', removed: 'This model has been removed from its provider', providerMissing: 'The matching provider configuration was not found', select: 'Select models to run in parallel', close: 'Close model picker', empty: 'Add a provider and model first', notConfigured: 'Not configured', clear: 'Clear selection', manage: 'Manage providers' },
      results: { title: 'Generated pages', demo: 'Demo mode · no external API calls', sandbox: 'Static results stay isolated · projects run on demand', reload: 'Reload examples', demoLoaded: 'Example results loaded', grid: 'GRID VIEW', queued: 'Queued', running: 'Generating', success: 'Artifact ready', error: 'Failed', copy: 'HTML copied to clipboard', copyLabel: 'Copy HTML', projectCopied: 'Project JSON copied to clipboard', copyProjectLabel: 'Copy project JSON', previewTitle: 'Page preview', copyError: 'Copy failed. Check browser permissions.', building: 'The model is building your page', wait: 'This usually takes a few seconds', waiting: 'Waiting to run', cancelled: 'Cancelled', cancelledCopy: 'This run was stopped', failed: 'This run did not finish', retry: 'Retry', expand: 'Expand preview', remove: 'Remove result', empty: 'Nothing to preview yet', staticBadge: 'Static', projectBadge: 'Project', fileCount: '{{count}} files', fileCount_one: '{{count}} file', fileCount_other: '{{count}} files', runProject: 'Run project', web: { booting: 'Starting WebContainer', mounting: 'Mounting project files', installing: 'Installing dependencies', starting: 'Starting project', ready: 'Project preview ready', stopping: 'Stopping project', error: 'Project failed to run', unsupported: 'WebContainer is unsupported in this browser', errorDescription: 'Check the truncated runtime log below for the startup problem.', unsupportedDescription: 'Retry with a modern browser that supports WebContainer.', switching: 'This preview is queued while the active project switches', stop: 'Stop', singleRuntime: 'SHARED ACTIVE PROJECT', waitingDescription: 'The first run installs dependencies and starts the dev server.', previewUnavailable: 'The container is ready but has not provided a preview URL.', logs: 'Runtime log' } },
      empty: { eyebrow: 'READY WHEN YOU ARE', title: 'Let ideas happen in parallel', copy: 'Choose models, write a direction, and Mosaic will give the same prompt to all of them.', select: 'Select models', demo: 'View example results' },
      providers: { title: 'Providers', count: '{{count}} providers', count_one: '{{count}} provider', count_other: '{{count}} providers', subtitle: 'Connect model services and run generations locally with your own keys.', add: 'Add provider', securityTitle: 'Your keys belong to this browser', securityCopy: 'Zustand persist stores configuration in localStorage. Use test keys and set provider limits.', configured: 'configured', connected: 'Connected providers', connectedCopy: 'Mix protocols to build your model pool', none: 'No providers yet', noneCopy: 'Add an API service and model to start your first parallel run.', first: 'Add the first one', addNew: 'Add a provider', addNewCopy: 'OpenAI · Anthropic · Gemini · Compatible API', keyReady: 'Key configured', keyMissing: 'API key needed', defaultUrl: 'SDK default URL', edit: 'Edit provider', delete: 'Delete provider', deleteConfirm: 'Delete {{name}}?', deleted: 'Provider deleted', footnote: 'You control model names, Base URLs and keys. Mosaic never proxies or uploads them.' },
      settings: { title: 'Settings', subtitle: 'Manage local workspace state and generation preferences.', localData: 'Local data', localCopy: 'All configuration is stored in this browser’s localStorage.', providerCount: 'Providers', configuredCount: 'Configured keys', selectedCount: 'Selected models', promptLength: 'Prompt length', restore: 'Restore defaults', restoreConfirm: 'Restore defaults? Current providers and prompt will be replaced.', restored: 'Default configuration restored', clear: 'Clear local configuration', clearConfirm: 'Clear all local configuration in this browser?', cleared: 'Local configuration cleared', security: 'Security boundary', securityCopy: 'This is a personal BYOK tool, not a production key vault.', localOnly: 'Keys stay in this browser', sandbox: 'Model output renders in a sandbox iframe', confirm: 'Confirm each model before running', warning: 'For production, use a backend proxy, set limits, and keep high-value keys off the client.', shortcuts: 'Shortcuts', shortcutCopy: 'Keep your prompt flow moving', run: 'Run generation', close: 'Close dialog / preview', add: 'Add provider' },
      dialog: { add: 'Add provider', edit: 'Edit provider', description: 'Keys stay in this browser’s local storage and are never sent to Mosaic servers.', name: 'Provider name', namePlaceholder: 'e.g. OpenRouter', protocol: 'Protocol', baseUrl: 'Base URL', key: 'API key', showKey: 'Show API key', hideKey: 'Hide API key', models: 'Model IDs', modelsPlaceholder: 'One model per line, e.g.\ngpt-4o\nmy-provider/model', urlHint: 'Changing the protocol updates the default URL. Confirm custom URLs match your model service.', modelHint: 'Prefer “Fetch models”. If the service has no model-list endpoint, keep manual entry as a fallback, one model per line.', fetchModels: 'Fetch models', fetchingModels: 'Fetching…', modelsFetched: 'Fetched {{count}} models', modelsFetched_one: 'Fetched {{count}} model', modelsFetched_other: 'Fetched {{count}} models', apiKeyRequired: 'Enter an API key first', security: 'This is a personal BYOK tool. Same-origin scripts can read local storage, so use test keys, set limits, and rotate them regularly.', cancel: 'Cancel', save: 'Save changes', delete: 'Delete provider', added: 'Provider added', updated: 'Provider updated' },
      theme: { label: 'Theme', appearance: 'Appearance', dark: 'Dark', light: 'Light', system: 'System', darkCopy: 'Dark workspace', lightCopy: 'Light workspace', systemCopy: 'Match this device' },
      language: { label: 'Language', chinese: '中文', english: 'English' },
      providerKind: { openai: 'OpenAI', anthropic: 'Anthropic', gemini: 'Google Gemini', 'openai-compatible': 'OpenAI compatible' },
      labels: { modelSet: 'MODEL SET', directive: '01 / DIRECTIVE', connections: '02 / CONNECTIONS', preferences: '03 / PREFERENCES', localConfig: 'LOCAL CONFIG', personalWorkspace: 'Personal workspace', modelStudio: 'MODEL STUDIO' },
      errors: { unknown: 'An unknown error occurred', network: 'Network request failed', cancelled: 'Request cancelled', requestFailed: 'Request failed: {{message}}', invalidResponse: 'The service returned an invalid response', validationFailed: 'Form validation failed' },
      validation: { name: 'Enter a provider name between 2 and 40 characters', baseUrl: 'Only HTTPS or local HTTP URLs are allowed', apiKey: 'The key length is invalid', models: 'Add at least one model' },
      common: { close: 'Close', loading: 'Loading', demo: 'DEMO' },
    },
  },
} as const

void i18n.use(LanguageDetector).use(initReactI18next).init({
  resources,
  fallbackLng: 'zh',
  supportedLngs: ['zh', 'en'],
  nonExplicitSupportedLngs: true,
  detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'], lookupLocalStorage: 'mosaic-language' },
  interpolation: { escapeValue: false },
})

export default i18n
